WebAppFirstCore/Controllers/BakeryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using WebAppFirstCore.Models;

namespace WebAppFirstCore.Controllers
{
    public class BakeryController : Controller
    {
        ICakeService _cakeService;

        public BakeryController(ICakeService cakeService)   //D.I.
        {
            _cakeService = cakeService;
        }

        public IActionResult Index()
        {
            return View(_cakeService.AllCakes());
        }
        [HttpPost]
        public IActionResult Index(string name, int price, string details)
        {
            _cakeService.CreateCake(name, price, details);

            return View(_cakeService.AllCakes());
        }

        public IActionResult AJAXPartialExample(int id)
        {
            return PartialView("_Cake", _cakeService.FindCake(id));
        }
    }
}

WebAppFirstCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/CSS/site.css" rel="stylesheet" />

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
</head>
<body>
    <header>
        <h1>Lexicon</h1>
        <nav>
            <ol>
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li>
                    @*@Html.ActionLink("Core", "Core")*@
                    <a asp-controller="Home" asp-action="Core">Core</a>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="Swing">Golf Swing</a>
                </li>
                <li>
                    <a asp-controller="Bakery" asp-action="Index">Bakery</a>
                </li>
                <li>
                    <a asp-controller="ToDoMemo" asp-action="Index">ToDo Session</a>
                </li>
            </ol>
        </nav>
    </header>
    <div class="viewbody">
        @RenderBody()
    </div>
    <div>
        <a id="aUpdate" 
            asp-controller="Bakery" 
            asp-action="AJAXPartialExample" 
            asp-route-id="0" 
            data-target="environment-container">Update</a>

        <div id="environment-container"></div>
    </div>
    <footer>
        <p>Made by: Ulf Bengtsson &copy;</p>
    </footer>

    <script>

        $("#aUpdate").click(function (e) {
            e.preventDefault();
            var _this = $(this);
            $.get(_this.attr("href"), function (res) {
                $('#' + _this.data("target")).html(res);
            });
        });

    </script>
</body>
</html>